name: GlyphControl
channels:
  - pytorch
  - defaults
  - conda-forge
  - nvidia/label/cuda-11.3.1
  - xformers/label/dev
dependencies:
  - python=3.9 
  - pip=20.3
  - cudatoolkit=11.3
  - cuda-nvcc=11.3
  - pytorch=1.12.1 
  - torchvision=0.13.1
  - torchaudio=0.12.1 
  - numpy=1.23.1 
  - xformers
  - pip:
    - pytorch-lightning==1.6.5 
    - omegaconf==2.1.1
    - einops==0.3.0
    - transformers==4.24.0 
    - open_clip_torch==2.0.2
    - gradio
    - tqdm
    - easyocr
    - ninja
    - triton==2.0.0.dev20221120
    - Levenshtein
    # - -e .
    # - albumentations==1.3.0 
    # - opencv-python #==4.6.0.66 # TODO: verfiy which version works
    # - opencv-python-headless<4.3 #TODO: verify
    # # - opencv-python-headless==4.5.3.56
    # # - opencv-python-headless==4.5.5.64
    # # - opencv-contrib-python==4.5.5.62
    # # - opencv-contrib-python-headless
    # - imageio==2.9.0
    # - imageio-ffmpeg==0.4.2
    # - wandb 
    # - sentencepiece 
    # - invisible-watermark>=0.1.5
    # - streamlit-drawable-canvas==0.8.0
    # - torchmetrics==0.6.0
    # - timm  
    # - webdataset==0.2.5
    # - kornia==0.6
    # - test-tube>=0.7.5
    # - streamlit==1.12.1 

